from src.exceptions.common.NotFoundError import NotFoundError


class UserNotExistsError(NotFoundError):
    pass
